name: my script

on:
  push:
    branches:
      - master

jobs:
  lets-start:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: copying project files
        uses: actions/checkout@v2.4.0

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: executes multiline script
        run: |
          node -v
          npm -v
          yarn -v

      - name: list of files after checkout
        run: |
          pwd
          ls -a
        shell: bash

      - name: Run npm install
        run: npm ci

      - name: Run Test
        run: npm run test:staging

      - name: Run Build
        run: npm run build --if-present

      # - name: SSH Remote server
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     key: ${{secrets.SSH_KEY}}
      #     host: ${{secrets.SSH_SERVER_IP}}
      #     username: ${{secrets.SSH_USER_NAME}}
      #     script: |
      #       cd /home/${{secrets.SSH_USER_NAME}}/app/action-hello
      #       git pull
      #       npm install

  # bydefault jobs run in parallel if we want to run one after another
  # we can use 'need'
  # runs-on-mac-os:
  #   runs-on: macos-latest
  #   # this job wait for print-something job to finish
  #   needs: [print-something]
  #   steps:
  #     - name: prints Hello
  #       run: echo "Hello from Mac"
